Exobioligy logic
rster2002/ed-journals pull request #15
Opened 2024-05-15 16:40 UTC by Somfic

Closes #13.

2024-05-15 16:50 UTC, rster2002 commented
You can probably target either. `json-files` is a separate branch because it uses a log of shared logic that is needed for basically all json files.

2024-05-15 16:51 UTC, rster2002 commented
And tests are failing because I was a bit sloppy when creating the `json-files` branch. Merging that one into yours should fix the failing tests.

2024-05-15 17:51 UTC, rster2002 commented on src/modules/exobiology/models/spawn_condition.rs
> +                true // FIXME: We need a way to get the parent star
This implementation can be moved to `SpawnSource` which would allow collecting information from multiple events and then feed it into this.

2024-05-15 17:52 UTC, rster2002 commented on src/modules/exobiology/models/spawn_condition.rs
> +                true // FIXME: We need a way to get the parent star
Then in `GameState` we could construct the `SpawnSource` (maybe rename it to something else) and use that to check possible spawns.

2024-05-15 18:08 UTC, Somfic commented on src/modules/exobiology/models/spawn_condition.rs
> +                true // FIXME: We need a way to get the parent star
Ah, great!

2024-05-15 19:01 UTC, Somfic commented on src/modules/exobiology/models/spawn_condition.rs
> +                true // FIXME: We need a way to get the parent star
> This implementation can be moved to `SpawnSource` which would allow collecting information from multiple events and then feed it into this.

Implemented this.



> Then in `GameState` you could construct the `SpawnSource` (maybe rename it to something else) and use that to check possible spawns.

Currently working on this.

2024-05-15 19:04 UTC, Somfic commented on src/modules/exobiology/models/spawn_source.rs
> +                self.star.luminosity >= *star_luminosity
This is a potential bug if we were to refactor `StarLuminosity`, what do you think?

2024-05-15 19:04 UTC, Somfic commented on src/modules/exobiology/models/spawn_source.rs
> +                //  result of planetary mapping to confirm signals are not present.
Need to do some more research on spawn conditions for geological signals.

2024-05-15 19:05 UTC, Somfic commented on src/modules/exobiology/models/spawn_source.rs
> +                //  indicate uncertainty about this spawn condition.
Are we fine with returning a simple boolean for this function? Or do we want to take into account situations where a species technically *could* spawn, but we know for certain after the commander maps the planet?

2024-05-15 19:26 UTC, rster2002 commented on src/modules/exobiology/models/spawn_source.rs
> +                //  result of planetary mapping to confirm signals are not present.
Geological signal spawn condition is for [fumerola](https://ed-dsn.net/en/fumerola_en/) which require a geological POI. A scan through the FSS or by proximity should indicate how many geological signals there are, so for this to return true there should be at least one geological signal. If there are none it cannot spawn anyway.

2024-05-15 19:29 UTC, rster2002 commented on src/modules/exobiology/models/spawn_source.rs
> +                self.star.luminosity >= *star_luminosity
Yeah you're right. Although I'm not sure what the correct ordering would in this when it comes to luminosity. The DSN article for the species that this applies to mentions class V or higher https://ed-dsn.net/en/electricae_en/

2024-05-15 19:32 UTC, rster2002 commented on src/modules/exobiology/models/spawn_source.rs
> +                //  indicate uncertainty about this spawn condition.
I think returning a bool for whether a species can technically spawn is fine. If a commander maps a planet it returns returns a `SAASignalsFoundEvent` which includes all the genuses. If you eventually want to find out which species are certain that could be implemented in `state` as that requires multiple events.

2024-05-15 19:34 UTC, rster2002 commented on src/modules/exobiology/models/spawn_source.rs
> +                self.star.luminosity >= *star_luminosity
You could add a function that returns a u8 value for each variant and base the ordering on that.

2024-05-15 19:46 UTC, Somfic commented on src/modules/exobiology/models/spawn_source.rs
> +                self.star.luminosity >= *star_luminosity
It looks like [0-class (hypergiant) luminosity is the brightest type of luminosity](https://www.youtube.com/watch?app=desktop&v=_Poi22a9Hzg), while having the lowest [absolute magintude](https://en.wikipedia.org/wiki/Absolute_magnitude). 

As the absolute magnitude of a star gets higher, the star becomes less bright. 

So for example an `Ia` (supergiant)’s luminosity is brighter than an `IV` (subgiant/dwarf)’s luminosity. So actually the expression is currently not implemented correctly and should be inverted (it smells of missing tests). 

The correct order (strong near top, weak near bottom) of luminosity is:
- 0
- Ia
- Ib
- II
- III
- IV
- V
- VI
- VII

2024-05-15 19:46 UTC, Somfic commented on src/modules/exobiology/models/spawn_source.rs
> +                self.star.luminosity >= *star_luminosity
> You could add a function that returns a u8 value for each variant and base the ordering on that.

[Ord](https://doc.rust-lang.org/std/cmp/trait.Ord.html) and [PartialOrd](https://doc.rust-lang.org/std/cmp/trait.PartialOrd.html) could come in to safe the day here. Those traits allow us to overload the `<`, `<=`, `>`, and `>=` operators.

2024-05-15 19:49 UTC, rster2002 commented on src/modules/exobiology/models/spawn_source.rs
> +                self.star.luminosity >= *star_luminosity
Yeah if you were to assign numbers you could do it in the same vein as how `LogFile` is ordered.

2024-05-15 22:22 UTC, Somfic commented
I’m in the progress of writing tests for these new functions using the test journals, but I’m getting some weird results… *Aleoida Coronamus* has as one of its spawn conditions a [max gavity of 0.27G](https://github.com/rster2002/ed-journals/blob/986d1e8d63a872ff95fc7c99241cb56b7604821b/src/modules/models/exploration/species.rs#L446). This is in line with what [ed-dsn](https://ed-dsn.net/en/aleoida_en/) and [canonn science](https://canonn.science/codex/aleoida-2/) report. 

However, that does not add up with our test journals:

1. Commander scans celestial body Phoi Aed NY-P d6-4 B 3 c. Has a surface gravity of 2.133268G: *(truncated version for clarity)*
https://github.com/rster2002/ed-journals/blob/fbebcefe4a336b0a8fde6370f4ac822f2fbd7837/test-journals/Journal.2024-01-31T194441.01.log#L76
```json
{
	"event": "Scan",
	"BodyName": "Phoi Aed NY-P d6-4 B 3c",
	"SurfaceGravity": 2.133268
	"SystemAddress": 148872824507,
	"BodyID": 38,
}
```

2. Commander touches down on the planet:
https://github.com/rster2002/ed-journals/blob/fbebcefe4a336b0a8fde6370f4ac822f2fbd7837/test-journals/Journal.2024-01-31T194441.01.log#L93

3. Commander disembarks from the ship:
https://github.com/rster2002/ed-journals/blob/fbebcefe4a336b0a8fde6370f4ac822f2fbd7837/test-journals/Journal.2024-01-31T194441.01.log#L97

4. Commander scans *Aleoida Coronamus* (note the matching SystemAddress and BodyID) *(truncated version for clarity)*:
https://github.com/rster2002/ed-journals/blob/fbebcefe4a336b0a8fde6370f4ac822f2fbd7837/test-journals/Journal.2024-01-31T194441.01.log#L104 
```json
{
	"event": "ScanOrganic",
	"Species_Localised": "Aleoida Coronamus",
	"SystemAddress": 148872824507,
	"Body": 38
}
```

This is rather odd, either *ed-dsn* **and** *canonn science* are incorrect (or maybe drawing knowledge from the same faulty source), or this was a bug in the game. How do we proceed @rster2002? Removing the journal from the test database feels like the wrong decision, unless we can confirm this was an in-game bug. I can do some more digging to see if this is the only occurrence, will have to rewrite the tests for that but I’m rather intrigued now.

anyhow i’m blaming the game; frontier pls fix

2024-05-16 05:57 UTC, rster2002 commented
I think it's fine to skip this test case then by either renaming the log file to end in `.skip` or filtering those specific events based on the timestamp or something.

It's either a bug or it is very very very rare that it spawns under these conditions (also looking at [the doc](https://docs.google.com/spreadsheets/d/15lqZtqJk7B2qUV5Jb4tlnst6i1B7pXlAUzQnacX64Kc))

2024-05-16 07:31 UTC, rster2002 commented on src/modules/exobiology/models/spawn_source.rs
> +                    star.class == *star_class
This doesn't yet seem to take into account systems with multiple stars. I'm not sure though what the behaviour should be if the planet has a `Null` parent. This is when the planet orbits multiple stars at the same time.

2024-05-16 07:32 UTC, rster2002 commented on src/modules/exobiology/models/spawn_source.rs
> +                    star.class == *star_class
Null parent look something like this: https://andreaszapf.de/blog/wp-content/uploads/2014/12/Image-09-Gas-Planet.jpg

2024-05-16 07:32 UTC, Somfic commented on src/modules/exobiology/models/spawn_source.rs
> +                    star.class == *star_class
Yes, still working on some of the spawn conditions

2024-05-16 07:44 UTC, Somfic commented
The `MaxGravity` condition seems to fail in a lot more test cases. 

```ini
'AleoidaCoronamus' on body 'Phoi Aed NY-P d6-4 B 3 c' fails [MaxGravity(0.27)]
'TussockCaputus' on body 'Phoi Aed NY-P d6-4 B 3 c' fails [MaxGravity(0.27)]
'FungoidaGelata' on body 'Phoi Aed NY-P d6-4 B 3 c' fails [Any([ThinAtmosphere(Water), All([ThinAtmosphere(ArgonRich), MinMeanTemperature(180.0), MaxMeanTemperature(195.0)])]), MaxGravity(0.27)]
'ReceptaUmbrux' on body 'Phoi Aed SY-Y d1-3 A 9 f' fails [MaxGravity(0.27)]
'TussockStigmasis' on body 'Phoi Aed SY-Y d1-3 A 9 f' fails [MaxGravity(0.27)]
'OsseusCornibus' on body 'Hypiae Aed AB-M d8-1 4' fails [MaxGravity(0.27)]
'TussockDivisa' on body 'Hypiae Aip CG-V d3-9 AB 1 c' fails [MaxGravity(0.27)]
'TussockVentusa' on body 'Phoi Aed CM-K d9-5 5 c' fails [MaxGravity(0.27)]
'TussockCapillum' on body 'Gludgooe NX-B d0 9' fails [PlanetClass(RockyBody), MaxGravity(0.27)]
'FungoidaBullarum' on body 'Gludgooe NX-B d0 9' fails [MaxGravity(0.27)]
'OsseusPumice' on body 'Gludgooe NX-B d0 9' fails [MaxGravity(0.27)]
'FonticuluaCampestris' on body 'Gludgooe NX-B d0 9' fails [MaxGravity(0.27)]
'TussockVentusa' on body 'Phoi Aed CM-K d9-5 5 d' fails [MaxGravity(0.27)]
'FungoidaSetisis' on body 'Hypiae Aed DL-N d7-2 C 1' fails [MaxGravity(0.27)]
'FrutexaMetallicum' on body 'Hypiae Aed DL-N d7-2 C 1' fails [MaxGravity(0.27)]
'TussockDivisa' on body 'Hypiae Aed DL-N d7-2 C 1' fails [PlanetClass(RockyBody), MaxGravity(0.27)]
'OsseusCornibus' on body 'Phoi Aed OH-C d2 3 c' fails [MaxGravity(0.27)]
'ClypeusSpeculumi' on body 'Phoi Aed OH-C d2 3 c' fails [MaxGravity(0.27), MinDistanceFromParentSun(5.0)]
'TussockTriticum' on body 'Phoi Aed OH-C d2 3 c' fails [MaxGravity(0.27)]
'CactoidaPullulanta' on body 'Phoi Aed OH-C d2 3 c' fails [MaxGravity(0.27)]
'AleoidaArcus' on body 'Phoi Aed NY-P d6-4 B 4 d' fails [MaxGravity(0.27)]
'TussockAlbata' on body 'Phoi Aed NY-P d6-4 B 4 d' fails [MaxGravity(0.27)]
'TubusConifer' on body 'Outorst OJ-Y b14-0 B 4 a' fails [MaxGravity(0.15)]
'TussockIgnis' on body 'Outorst OJ-Y b14-0 B 4 a' fails [MaxGravity(0.27)]
'ClypeusSpeculumi' on body 'Hypiae Aed TE-F d12-1 4 f' fails [MaxGravity(0.27), MinDistanceFromParentSun(5.0)]
'TussockTriticum' on body 'Hypiae Aed TE-F d12-1 4 f' fails [MaxGravity(0.27)]
'TussockDivisa' on body 'Outorst AG-W b15-0 C 6' fails [PlanetClass(RockyBody), MaxGravity(0.27)]
'FungoidaSetisis' on body 'Outorst AG-W b15-0 C 6' fails [MaxGravity(0.27)]
'AleoidaArcus' on body 'Ploea Theia YI-B d3 A 8' fails [MaxGravity(0.27)]
'FrutexaMetallicum' on body 'Ploea Theia TI-B d1 A 7' fails [MaxGravity(0.27)]
'AleoidaArcus' on body 'Ploea Theia TI-B d1 A 7' fails [MaxGravity(0.27)]
'TussockAlbata' on body 'Ploea Theia TI-B d1 A 7' fails [PlanetClass(RockyBody), MaxGravity(0.27)]
'ReceptaConditivus' on body 'Hypiae Aip XL-B d14-2 4 a' fails [MaxGravity(0.27)]
'FungoidaSetisis' on body 'Phoi Aed EX-I d10-3 1 a' fails [MaxGravity(0.27)]
'AleoidaSpica' on body 'Phoi Aed EX-I d10-3 1 a' fails [MaxGravity(0.27)]
'FrutexaFlabellum' on body 'Phoi Aed EX-I d10-3 1 a' fails [MaxGravity(0.27)]
'OsseusSpiralis' on body 'Gludgooe MC-C d0 9 b' fails [MaxGravity(0.27)]
'FungoidaGelata' on body 'Hypiae Aip SN-A d1-8 10 c' fails [Any([ThinAtmosphere(Water), All([ThinAtmosphere(ArgonRich), MinMeanTemperature(180.0), MaxMeanTemperature(195.0)])]), MaxGravity(0.27)]
'TussockCaputus' on body 'Hypiae Aip SN-A d1-8 10 c' fails [MaxGravity(0.27)]
'ConchaRenibus' on body 'Hypiae Aip SN-A d1-8 10 c' fails [Any([All([MaxGravity(0.27), Any([ThinAtmosphere(CarbonDioxide), ThinAtmosphere(CarbonDioxideRich)]), MinMeanTemperature(180.0), MaxMeanTemperature(195.0)]), All([MaxGravity(0.27), Any([ThinAtmosphere(Water), ThinAtmosphere(WaterRich)])])])]
'FungoidaSetisis' on body 'Hypiae Aed VP-D d13-0 5 c' fails [MaxGravity(0.27)]
'ConchaLabiata' on body 'Hypiae Aip XL-B d14-2 5 c' fails [MaxGravity(0.27)]
'TubusConifer' on body 'Hypiae Aip XL-B d14-2 5 c' fails [MaxGravity(0.15)]
'TussockIgnis' on body 'Hypiae Aip XL-B d14-2 5 c' fails [MaxGravity(0.27)]
'FrutexaFlabellum' on body 'Ploea Theia AK-Z d1 ABC 2 b' fails [MaxGravity(0.27)]
'AleoidaSpica' on body 'Ploea Theia AK-Z d1 ABC 2 b' fails [MaxGravity(0.27)]
'FungoidaSetisis' on body 'Ploea Theia AK-Z d1 ABC 2 b' fails [MaxGravity(0.27)]
'TussockDivisa' on body 'Ploea Theia AK-Z d1 ABC 2 b' fails [MaxGravity(0.27)]
'ConchaAureolas' on body 'Ploea Theia AK-Z d1 ABC 2 b' fails [MaxGravity(0.27)]
'TussockDivisa' on body 'Hypiae Aip VK-M d8-9 10 d' fails [MaxGravity(0.27)]
'AleoidaSpica' on body 'Hypiae Aip VK-M d8-9 10 d' fails [MaxGravity(0.27)]
'OsseusSpiralis' on body 'Hypiae Aip VK-M d8-9 10 d' fails [MaxGravity(0.27)]
'CactoidaPullulanta' on body 'Hypiae Aip SN-A d1-8 10 d' fails [MaxGravity(0.27)]
'FungoidaGelata' on body 'Hypiae Aip SN-A d1-8 10 d' fails [Any([ThinAtmosphere(Water), All([ThinAtmosphere(ArgonRich), MinMeanTemperature(180.0), MaxMeanTemperature(195.0)])]), MaxGravity(0.27)]
'TussockCaputus' on body 'Hypiae Aip SN-A d1-8 10 d' fails [MaxGravity(0.27)]
'FonticuluaCampestris' on body 'Wredguia HN-Z b27-0 A 8' fails [MaxGravity(0.27)]
'FonticuluaCampestris' on body 'Wredguia IN-Z b27-2 10 c' fails [MaxGravity(0.27)]
'TussockDivisa' on body 'Gludgooe PP-N d7-8 5' fails [PlanetClass(RockyBody), MaxGravity(0.27)]
'AleoidaSpica' on body 'Gludgooe PP-N d7-8 5' fails [MaxGravity(0.27)]
'TussockSerrati' on body 'Phoi Aed PJ-O d7-3 1 c' fails [MaxGravity(0.27)]
'TubusConifer' on body 'Phoi Aed PJ-O d7-3 1 c' fails [MaxGravity(0.15)]
'FonticuluaCampestris' on body 'Phoi Aed ID-H d11-2 4 a' fails [MaxGravity(0.27)]
'ElectricaePluma' on body 'Phoi Aed ID-H d11-2 4 a' fails [ParentStarClass(A), Any([MinOrEqualParentStarLuminosity(V), ParentStarClass(N)]), MaxGravity(0.27)]
'FonticuluaUpupam' on body 'Hypiae Aip WL-B d14-14 ABC 1 d' fails [ThinAtmosphere(Argon), MaxGravity(0.27)]
'TubusConifer' on body 'Gludgae PI-I d10-1 6 a' fails [MaxGravity(0.15)]
'AleoidaArcus' on body 'Gludgae PI-I d10-1 6 a' fails [MaxGravity(0.27)]
'TubusConifer' on body 'Hypiae Aip XL-B d14-1 C 3 c' fails [MaxGravity(0.15)]
'TussockIgnis' on body 'Hypiae Aip XL-B d14-1 C 3 c' fails [MaxGravity(0.27)]
'ConchaLabiata' on body 'Hypiae Aip XL-B d14-1 C 3 c' fails [MaxGravity(0.27)]
'TussockVentusa' on body 'Phoi Aed CM-K d9-5 5 b' fails [MaxGravity(0.27)]
'TussockVentusa' on body 'Phoi Aed CM-K d9-5 5 a' fails [MaxGravity(0.27)]
'AleoidaArcus' on body 'Hypiae Aip WL-B d14-14 ABC 1 b' fails [MaxGravity(0.27)]
'TussockAlbata' on body 'Hypiae Aip WL-B d14-14 ABC 1 b' fails [MaxGravity(0.27)]
'OsseusSpiralis' on body 'Wregoe YL-L d8-7 6' fails [MaxGravity(0.27)]
'ReceptaConditivus' on body 'Hypiae Aip VK-M d8-9 9 e' fails [MaxGravity(0.27)]
'TussockIgnis' on body 'Hypiae Aip XL-B d14-1 C 3 d' fails [MaxGravity(0.27)]
'TubusConifer' on body 'Hypiae Aip XL-B d14-1 C 3 d' fails [MaxGravity(0.15)]
'ConchaLabiata' on body 'Hypiae Aip XL-B d14-1 C 3 d' fails [MaxGravity(0.27)]
'CactoidaLapis' on body 'Futes C 5' fails [MaxGravity(0.27)]
'TussockSerrati' on body 'Phoi Aed PJ-O d7-3 2 c' fails [MaxGravity(0.27)]
'TussockAlbata' on body 'Swoilz DR-A c2-2 A 6' fails [PlanetClass(RockyBody), MaxGravity(0.27)]
'TussockDivisa' on body 'Hypiae Aip TN-A d1-5 2 b' fails [MaxGravity(0.27)]
'CactoidaPullulanta' on body 'Phoi Aed PJ-O d7-3 1 b' fails [MaxGravity(0.27)]
'AleoidaCoronamus' on body 'Phoi Aed PJ-O d7-3 1 b' fails [MaxGravity(0.27)]
'FungoidaGelata' on body 'Phoi Aed PJ-O d7-3 1 b' fails [Any([ThinAtmosphere(Water), All([ThinAtmosphere(ArgonRich), MinMeanTemperature(180.0), MaxMeanTemperature(195.0)])]), MaxGravity(0.27)]
'TussockCaputus' on body 'Phoi Aed PJ-O d7-3 1 b' fails [MaxGravity(0.27)]
'ConchaRenibus' on body 'Phoi Aed PJ-O d7-3 1 b' fails [Any([All([MaxGravity(0.27), Any([ThinAtmosphere(CarbonDioxide), ThinAtmosphere(CarbonDioxideRich)]), MinMeanTemperature(180.0), MaxMeanTemperature(195.0)]), All([MaxGravity(0.27), Any([ThinAtmosphere(Water), ThinAtmosphere(WaterRich)])])])]
'OsseusSpiralis' on body 'Swoi [...]

2024-05-16 07:56 UTC, rster2002 commented
I've been looking at how Elite Observatory does things https://github.com/Xjph/ObservatoryCore/tree/master/ObservatoryBotanist but also can't find where they have their spawn conditions set.

2024-05-16 08:47 UTC, Somfic commented
> anyhow i’m blaming the game; frontier pls fix

welp... i'm a moron..

`G` denotes the gravity in Earth's gravity. 1G is equivalent to the same gravity we experience on Earth. However, the game does not output `SurfaceGravity` in `G`s, but in `m/s^2`. So, we have to divide `SurfaceGravity` by Earth's fall acceleration caused by gravity, 9.81m/s^2 to get to the unit of `G`.

This can be confirmed with the following `Scan` entry: *(truncated for clearity)*
```json
{ 
	"timestamp":"2023-01-04T09:00:44Z", 
	"event":"Scan", 
	"BodyName":"Flyae Proae YU-V d3-2 1",
	"SurfaceGravity":4.227870,
}
```
and [EDSM's entry for this body](https://www.edsm.net/en/system/bodies/id/77837260/name/Flyae+Proae+YU-V+d3-2/details/idB/423777113/nameB/Flyae+Proae+YU-V+d3-2+1) denoting this as 0.43G. 4.227870 / 9.81 = 0.43G.

This would fix our test cases, for example the previously mentioned Aleoida Coronamus on Phoi Aed NY-P d6-4 B 3 c with a gravity of 2.133268 / 9.81 = 0.217G, which is within the 0.27G maximum.

so.. game not bugged.. me code bugged :)

2024-05-16 08:57 UTC, Somfic commented
Is it an idea to create a `Gravity` type with an `as_ms2` and `as_g` for the `SurfaceGravity` field? Would rather have to call an extra function than double checking documentation to make sure I'm doing maths with the correct units. What do you think?

2024-05-16 15:26 UTC, rster2002 commented
I think that's a good solution, although you would still need to make sure that Gravity isn't used in serde somewhere where it is expected in Gs stead of m/s^2, but I think planets are the only place where gravity is logged so it should be fine.

2024-05-16 16:10 UTC, Somfic commented
> I think that's a good solution, although you would still need to make sure that Gravity isn't used in serde somewhere where it is expected in Gs stead of m/s^2, but I think planets are the only place where gravity is logged so it should be fine.

The journals indicate only the `SurfaceGravity` field in a `Scan`entry is used to indicate gravity, which is always in m/s2. I’ve implemented the `Deserialize` and `Serialize` traits to always (de)serialize to m/s2.

2024-05-16 16:16 UTC, rster2002 commented on src/modules/logs/content/log_event_content/scan_event.rs
> +}
I would maybe suggest picking either Ms2 or G variant and turning it into something like

```rust
/// Gravity in m^2
pub struct Gravity(pub f32);
```

This allows you to just derive deserialize and simplifies it a bit.

2024-05-16 16:24 UTC, Somfic commented on src/modules/logs/content/log_event_content/scan_event.rs
> +}
Good catch, using a struct works much simpler here :)

2024-05-16 18:58 UTC, rster2002 commented
A shit this targeted json-files

2024-05-17 01:12 UTC, Somfic commented on src/modules/logs/content/log_event_content/scan_event.rs
> +    pub distance_from_arrival_ls: Distance,
With the `Distance` type we could probably rename this to just `distance_from_arrival`?

2024-05-17 01:18 UTC, Somfic commented on src/modules/exobiology/models/spawn_source.rs
> +            distance_from_nebula: None, // FIXME: No idea how to get this data yet.
As per the comment I have no clue how to get this information, journals don’t seem to expose this information. There’s around ~110 nebulae in Elite (source i just read some random reddit comment), do we want to hardcode them and then use the cartesian distance; $\sqrt{dx^2 + dy^2 + dz^2}$?

2024-05-17 01:19 UTC, Somfic commented on src/modules/exobiology/models/spawn_source.rs
> +            }
Still need to fix this, leaving a comment here so I don’t forget.

2024-05-17 06:30 UTC, rster2002 commented on src/modules/exobiology/models/spawn_source.rs
> +            distance_from_nebula: None, // FIXME: No idea how to get this data yet.
Yes that was my idea. And I already have some setup on how to get these values so you don't have to worry about it right now.

2024-05-17 06:40 UTC, rster2002 commented on src/modules/logs/content/log_event_content/scan_event.rs
> +    pub distance_from_arrival_ls: Distance,
That's fine. Maybe then rename the struct to `DistanceLS` to make it clear in the type name what the float represents.

2024-05-17 11:02 UTC, Somfic commented
I’m starting to think that when dsn refers to a ‘Rocky planet’ they’re not necessarily  referring to the planet type being ’Rocky body’ but to the planet’s composition containing `Rock`. 

For example, I’m finding Tussock Cultro on a high metal content body (Swoilz VE-E c6 A 5), which is made of 67% rock.

I suggest adding a `RockyComposition` condition, and leaving `PlanetClass` as is. Thoughts?

2024-05-17 11:33 UTC, rster2002 commented
If you think that that would give more accurate results then go for it. Though I'm not sure about the other planet types like for example what the difference would be between `PlanetClass::MetalRichBody` and `PlanetClass::HighMetalContentBody`.

2024-05-17 11:41 UTC, Somfic commented
I am currently only testing against false negatives by testing against the journal files. I’ll also have to write tests for false positives. As for now technically if `get_spawnable_species` would return all the known species the tests would still pass

2024-05-17 14:30 UTC, rster2002 commented
Just merged a PR that optimizes the spawn spawn conditions for species so it doesn't allocate on every call. `spawn_conditions` now returns a `&Vec<SpawnCondition>`.

2024-05-17 17:19 UTC, rster2002 commented
Just merged it to `master`

2024-05-17 18:03 UTC, Somfic commented
Great, thanks! Would you consider tracking the current StarPos (only exposed in `Location` and `FsdJump` events) to be in the scope of `SpawnSource`? Seems like the wrong place for it. If we don't we'll have to pass the current starpos to `get_spawnable_species`. And track it somewhere else, perhaps in `ExobiologyState`?

2024-05-17 18:19 UTC, rster2002 commented
Well, the way I see it is that exo predictions can be calculated for any system, not just the current one, so that you could also see if you missed any biologicals in previous systems.

Constructing the SpawnSource should contain _a_ position, but doesn't necessarily need to be the current system.

2024-05-17 19:48 UTC, rster2002 commented on src/modules/logs/content/log_event_content/scan_event.rs
> +        DistanceLs(ly / 31556926.0)
Shouldn't this be `ly * 31556926.0`?

2024-05-17 19:49 UTC, Somfic commented on src/modules/logs/content/log_event_content/scan_event.rs
> +        DistanceLs(ly / 31556926.0)
Yeah, brainfart. Already fixed and added a test!

2024-05-17 19:51 UTC, Somfic commented
Okay, all the functionalities should be implemented now! 

Tests are currently failing for some rare instances where species are spawning where they shouldn't. For example: Osseus Discus spawning on a body without a thin water atmosphere (Prie Chraea VL-L c21-0 1 c).

2024-05-17 20:19 UTC, rster2002 commented
Yeah I'm also not entirely sure what to do in those cases. The spawn conditions are of course based on observation and not based on datamining or something like that, so the rules may not even be accurate, but I also would like to keep the list of potential species as short as possible. 

Do you know how many of these cases there are vs successful cases? If it's very small I would actually just remove those lines from the test suite as I would consider having 100% accuracy for predictions out of scope.

2024-05-17 20:30 UTC, Somfic commented
> Yeah I'm also not entirely sure what to do in those cases. The spawn conditions are of course based on observation and not based on datamining or something like that, so the rules may not even be accurate, but I also would like to keep the list of potential species as short as possible.
> 
> Do you know how many of these cases there are vs successful cases? If it's very small I would actually just remove those lines from the test suite as I would consider having 100% accuracy for predictions out of scope. 95% is also already a good number if that means ignoring those edge cases.

13 / 2631 are currently failing. I’ll remove them out of the test suite after double checking each with the docs from dsn and the journal scan entry.

2024-05-17 21:27 UTC, rster2002 requested changes
The prediction logic itself already seems to work very well. Most of these comments are about what roles the different parts of the code base should play, and they're largely related to keeping the code consistent.

But besides that: awesome work 🎉  also very nice that you also implemented a good number of tests for the code added.

2024-05-17 21:27 UTC, rster2002 commented on src/modules/state/models/exobiology_state.rs
> +
Taking into account the previous comment about the SpawnSource here's what I would do:

1. Make it so that exobiology state is part of the `SystemState`
2. Collect all data from events that you need for the SpawnSource.
3. Add a function to the `SystemStatet` that takes a body_id. Than will then use the state in the exobiology state to construct the SpawnSource and from that you can return the predictions.

This is probably not the only way to do this, but I think that this would be more in line with what state vs spawn state is used for.

2024-05-17 21:40 UTC, Somfic commented on src/modules/exobiology/models/spawn_source.rs
> +            "Flyoo Groa TQ-Y c3-4 C 1".to_string(), // ElectricaeRadialem spawned 32kly away from a nebula      // FIXME: See above
The data seems to indicate there’s a nebula around these systems that’s not in our `Nebula` enum yet.

2024-05-17 21:44 UTC, Somfic commented
Tests are all-green after blacklisting 10 bodies! 4 of which are nebula-related, probably just missing a nebula in our enum.

2024-05-17 21:53 UTC, rster2002 commented on src/modules/exobiology/models/spawn_source.rs
> +            "Flyoo Groa TQ-Y c3-4 C 1".to_string(), // ElectricaeRadialem spawned 32kly away from a nebula      // FIXME: See above
Sheesh that's far out https://www.edsm.net/en/system/id/9889385/name/Flyoo+Groa+XW-W+c4-13 I'll check in-game tomorrow

2024-05-18 11:12 UTC, rster2002 commented on src/modules/exobiology/models/spawn_source.rs
> +            "Flyoo Groa TQ-Y c3-4 C 1".to_string(), // ElectricaeRadialem spawned 32kly away from a nebula      // FIXME: See above
Just pushed the nebula that was related to this one. Going through the galaxy map though there are probably still a lot missing, so maybe I'll just spend an afternoon at one point going through the galaxy map and adding the nebula that I come across.

2024-05-18 11:30 UTC, Somfic commented on src/modules/exobiology/models/spawn_source.rs
> +            "Flyoo Groa TQ-Y c3-4 C 1".to_string(), // ElectricaeRadialem spawned 32kly away from a nebula      // FIXME: See above
Awesome thanks! :)

2024-05-18 12:18 UTC, Somfic commented
I was wondering why `SystemState` derives `serder::Serialize`? This’d cascade to pretty much everything related to state to have to implemented `Serialize`, was that intended?

2024-05-18 13:01 UTC, rster2002 commented
Yeah, this is intentional. The idea being that by making the state serializable it's easier for applications what would use this library to take parts (or the whole state) and pass it around. Not making it serializable would mean that applications would basically have to create a separate models and then need to copy data around which I was trying to avoid.

One thing I did consider doing and ended up not doing was putting serialize behind a feature flag, but I found that would add unnecessary complexity vs just making everything serializeable.

2024-05-19 11:12 UTC, Somfic commented on src/modules/state/models/exobiology_state.rs
> +
Implemented!

2024-05-19 11:12 UTC, Somfic commented on src/modules/exobiology/models/spawn_source.rs
> +    }
Implemented!

2024-05-19 11:15 UTC, Somfic commented
Doing everything in `ExobiologyState` seems to work well. Do we want the `exobioligy` field in `SystemState` to be pub and have the user retrieve a SpawnSource using `systemstate.exobioligy.get_for_body()` or do we want a function in `SystemState`; `systemstate.get_exobioligy_for_body()`?

2024-05-19 11:21 UTC, Somfic commented on src/modules/state/models/exobiology_state.rs
> +}
Should we move this into an `impl` for `Nebula` instead?

2024-05-19 11:43 UTC, rster2002 commented
I think making exobiology `pub` and adding `systemstate.exobioligy.get_for_body()` is a good option.

2024-05-19 11:45 UTC, rster2002 commented on src/modules/state/models/exobiology_state.rs
> +}
Yes that's a good idea. Eventually I would also want to move `calculate_distance` into the `galaxy` module so it can be used at more placed in the library, but that comes at a later time.

2024-05-19 11:46 UTC, rster2002 commented
Also don't worry about the merge conflicts. Just give a signal and I'll merge those. I've moved some things around so once you're ready to merge I'll resolve those for you.

2024-05-19 12:06 UTC, Somfic commented
Okay, everything’s good to go from my end!

2024-05-19 12:07 UTC, rster2002 approved these changes
Very happy with the implementation. A couple of optimizations could still be made, but nothing that should keep this from getting merged.

2024-05-19 12:40 UTC, merged